### ISSUE TITLE
A css version

### ISSUE THREAD

**Issue by egorsmkv** [Omi0/boostrap-mixins#1]
Can you provide a css file compiled from the scss file, please?

**Comment by timsergeev** [comment]
Of course I am not. Those mixins are depends on the your custom variables, breakpoints, etc. Why don't you use sass preprocessor?

**Comment by egorsmkv** [comment]
I meant to create a compiled version with standard Bootstrap's files. I am not much familiar with front-end technologies so it is complicated for me.

**Comment by egorsmkv** [comment]
Althought, I think it will be better if you add gulp scripts to the repository in order anyone could compile CSS files.
